/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ibia.app;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App app = new App();
        assertNotNull("app should have a greeting", app);
    }
}
